import { useState } from 'react';
import Head from 'next/head';
import Header from '../components/Header/Header';
import Hero from '../components/Hero/Hero';
import HeroCards from '../components/HeroCards/HeroCards';
import Products from '../components/Products/Products';
import Footer from '../components/Footer/Footer';

export default function Home({ products, user }) {
  const [loading, setLoading] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [productsPerPage] = useState(16);

  //GET CURRENT PRODUCTS
  const indexOfLastProduct = currentPage * productsPerPage;
  const indexOfFirstProduct = indexOfLastProduct - productsPerPage;
  const currentProducts = products.slice(
    indexOfFirstProduct,
    indexOfLastProduct
  );

  return (
    <div>
      <Head>
        <title>Aerolab Store</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Header user={user} />
      <Hero />
      <HeroCards />
      <Products
        products={currentProducts}
        user={user}
        loading={loading}
        setLoading={setLoading}
        currentPage={currentPage}
        setCurrentPage={setCurrentPage}
        productsPerPage={productsPerPage}
        totalProducts={products.length}
      />
      <Footer />
    </div>
  );
}

//GET PRODUCTS && USER

export async function getServerSideProps() {
  const res = await fetch('https://coding-challenge-api.aerolab.co/products', {
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      Authorization: `Bearer ${process.env.REACT_APP_AEROLAB_TOKEN}`,
    },
  });

  const resUser = await fetch(
    'https://coding-challenge-api.aerolab.co/user/me',
    {
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        Authorization: `Bearer ${process.env.REACT_APP_AEROLAB_TOKEN}`,
      },
    }
  );

  const products = await res.json();
  const user = await resUser.json();

  return { props: { products, user } };
}
